### ISSUE TITLE
Emporia smart plug

### ISSUE THREAD

**Issue by AlexVercammen** [magico13/ha-emporia-vue#14] opened 2020-10-24 16:57 UTC
I bought a couple of their smart plugs. I have them setup in their app. as merged with the main circuit. Great, they both show up as soon as I restarted Hassio. However, I can see the app. has an On/Off option. 

Enhancement: Is it possible to add that option to your plugin as a switch or service?

**Comment by magico13** [comment] 2020-10-24 17:36
It's on my list of things to look into when I next sit down to work on this. I somewhat recently added that functionality to the library this addon is based on (see https://github.com/magico13/PyEmVue/issues/7) specifically to allow you to control it from home assistant.

**Comment by AlexVercammen** [comment] 2020-10-27 19:47
I have a some programming skills. However, working under the Hassio integration of EmporiaVue, I am at a loss on how to leverage the information (python scripts) included in the PyEmVue link you've provided. Hassio has listed both plugs correctly under the EmporiaVue integration. How do I build a service using some your PyEmVue python code to control them?
Or is it impossible until you update the EmporiaVue add-on?
I apologize in advance if my queries are trivial for a programmer... I am more focused on business/desktop applications.

**Comment by magico13** [comment] 2020-10-27 20:01
The Home Assistant addon doesn't use that version of the library yet. When I update this to use that version then I can include a service or similar that ultimately calls into the PyEmVue library to flip the switch. Right now there's no way to do that since the current version of the addon doesn't even know they're plugs, it just thinks they're a regular sensor or a part of the gateway expansion basically.

My comment before was just that it's coming to this at some point since I added the required code to the library this uses for all its communication with the Emporia API, which is the prereq of adding a service/device that can do it to Home Assistant.

**Comment by AlexVercammen** [comment] 2020-10-27 20:09
Got you. I had a feeling what your response would be "impossible" as I could not see/understand the connection between the library and the API. I guess I am not as "dumb" as I've imagined. 👍

**Comment by haddood** [comment] 2020-11-10 06:12
thank you for all the hardwork

**Comment by AlexVercammen** [comment] 2020-11-10 11:26
Cool. I will check it out tonight. Thank you. Hell of an integration! Thank you for the work.

**Comment by magico13** [comment] 2020-11-10 13:07
Sorry if closing that other issue was misleading, I haven't done this yet, that one was a duplicate of this.

**Comment by magico13** [comment] 2020-11-22 22:17
Implemented in v0.2.0

**Closed by magico13** 2020-11-22 22:17 UTC
Labels: enhancement
