### ISSUE TITLE
home assistant Log shows error

### ISSUE THREAD

**Issue by armdan** [magico13/ha-emporia-vue#12] opened 2020-09-28 03:57 UTC
Logger: homeassistant.util.async_
Source: util/async_.py:105 
First occurred: 8:54:30 PM (9 occurrences) 
Last logged: 8:54:36 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/__init__.py, line 61: result = vue.login(username=email, password=password)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/sensor.py, line 15: vue_devices = vue.get_devices()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/sensor.py, line 20: device = vue.populate_device_properties(device)

**Comment by skynet01** [comment] 2020-09-28 06:58
I am getting the same errors. I am also getting random occurrences where the sensors just stop reporting. Checking the Vue app everything seems to be working ok on their end.

**Comment by magico13** [comment] 2020-09-28 13:02
This is a duplicate of #2 but thanks for the report. @skynet01 I haven't seen that issue personally. If you're able to narrow it down at all (happens after running for a certain amount of time, etc) please open a new issue and I can see what I can find.

**Closed by magico13** 2020-09-28 13:02 UTC
Labels: duplicate

**Comment by error420** [comment] 2020-11-09 14:06
This happens every time home assistant is restarted.
