### ISSUE TITLE
1 second pulling isn’t loading

### ISSUE THREAD

**Issue by tytemple** [magico13/ha-emporia-vue#43] opened 2021-05-08 03:24 UTC

**Comment by cajuncoding** [comment] 2021-05-10 02:48
Mine works for a while but then occasionally stops.  I checked the other day and it was working again -- maybe due to restarting things.  But yea it has definitely stopped randomly for me (with no errors that I can find so far).

**Comment by tsukraw** [comment] 2021-05-10 17:39
Mine stops from time to time as well.  A reload of the addon always seems to correct it.
Maybe there could be some kind of watchdog service added so it re-tries after X amount of time?

**Comment by magico13** [comment] 2021-05-10 17:48
The way it works, as long as the sensor gets set up correctly when Home Assistant starts then it will poll every second. If it fails then a second later it polls again. So the loss of any one second shouldn't really matter because it will try again almost immediately and should keep doing that forever.

Sometimes the API stops giving 1 second data correctly and will just report null data. That happened yesterday pretty noticeably when they updated the app and invalid data was being sent for a good hour or so. There's not much I can do in that case except keep retrying.

It used to be that if you started the server and the API gave bad data the sensor wouldn't get set up and you'd have to reload it to get those sensors back. That shouldn't be the case with v0.4.0 since if it fails during setup then it should trigger the built-in retry logic that Home Assistant has. There's also additional logging around those sorts of errors. If you keep seeing issues with v0.4.0 and the sensor going unavailable for long periods of time then let me know.

**Comment by tsukraw** [comment] 2021-05-10 18:15
Makes sense.  
I updated mine yesterday to v0.4.0 
Ill keep any eye on it and report back.

**Comment by tsukraw** [comment] 2021-05-13 17:11
Hey @magico13 
So the issue came up again.
What is odd is the main power continued to work on 1 second., it never stopped. 
But all the sub sensors stopped all working on 1 second at the same time. 
I have let it sit for now 12+hrs and it hasn't come back.   It is still in the broken state, I suspect if I do a reload it will fix.

Is there any logs I can grab while it is in the broken state that would help identify the issue?

**Comment by magico13** [comment] 2021-05-13 17:24
That's the second report of the main sensors working but the sub-sensors breaking, definitely a weird situation. If you see anything in the logs page regarding Emporia Vue then I'd appreciate it if you copy and paste them into here but most likely I'll have to do some testing to see if I can reproduce it. It's possible they made some more backend API changes that I'm not handling correctly, or some of my other changes could have messed things up after running for a while.

**Comment by tsukraw** [comment] 2021-05-13 17:32
Here is from the logs. 
I just did a "reload" and it resolved the issue....

Error fetching sensor data: Error communicating with Emporia API: HTTPSConnectionPool(host='api.emporiaenergy.com', port=443): Max retries exceeded with url: /AppAPI?apiMethod=getDevicesUsage&deviceGids=43699&instant=2021-05-13T14:51:36.001960Z&scale=1MIN&energyUnit=KilowattHours (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd4c51af820>: Failed to establish a new connection: [Errno -3] Try again'))
12:11:42 PM – (ERROR) Emporia Vue (custom integration) - message first occurred at May 12, 2021, 2:16:21 PM and shows up 12 times
Error communicating with Emporia API: HTTPSConnectionPool(host='api.emporiaenergy.com', port=443): Max retries exceeded with url: /AppAPI?apiMethod=getDevicesUsage&deviceGids=43699&instant=2021-05-13T14:51:36.001960Z&scale=1MIN&energyUnit=KilowattHours (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd4c51af820>: Failed to establish a new connection: [Errno -3] Try again'))
12:11:42 PM – (ERROR) Emporia Vue (custom integration) - message first occurred at May 12, 2021, 2:16:21 PM and shows up 12 times

**Comment by Sc00bs110** [comment] 2021-08-03 07:58
Seems that the latest release is only querying the Emproa server once a minute now due to restrictions on the API. 
I think that we should put pressure on them to either 
1. Allow more API requests or
2. Allow an update of a local MQTT server with the power readings
I would prefer a cloudless option if possible.

**Comment by magico13** [comment] 2021-08-07 02:03
I am interested in seeing what the rate limit will be when the official API comes out but I am not holding my breath for more than 2k requests a day. I'd love to see MQTT support but they've been pretty opposed to local data since their business model is cloud based and they want to use your data.

Since this issue isn't really relevant anymore since 0.5.0 I'm going to close this.

**Closed by magico13** 2021-08-07 02:03 UTC

**Comment by Sc00bs110** [comment] 2021-08-07 06:38
Sounds like their business model revolves around the monetization of the energy data. Don't see how that restricts them from being able to provide local MQQT updates to us (maybe cause people would shut of their internet access for the device?) but if they keep the requests so low (low server resources on their side maybe), the only route that will be left then is either to reflash the device or move to another platform that gives the granularity we want. I looked at the  https://circuitsetup.us/product/expandable-6-channel-esp32-energy-meter/ before I bought the Emporia Vue and am starting to think I maybe should have gone that way.  Hopefully they just give us the data we want, that would really be the easiest.

**Comment by Sc00bs110** [comment] 2021-08-07 06:39
Maybe we should start an online petition or something to see if we can put some pressure on them?

**Comment by Sc00bs110** [comment] 2021-08-07 06:46
Interesting Tear Down on the board https://www.youtube.com/watch?v=Ph9344O7DEs
