### ISSUE TITLE
Emporia Vue

### ISSUE THREAD

**Issue by davidjbwatson** [magico13/ha-emporia-vue#29] opened 2021-02-10 23:44 UTC
Good to see I am not the only one with this issue. I have also tried reinstalling . No entity or devices . this way for two days now.
Re installing all procedures fine but no loggingas no device.

**Comment by chanders** [comment] 2021-02-11 19:51
Same issue here running Version 3.0

**Comment by magico13** [comment] 2021-02-11 20:31
I'm going to close this as a duplicate of #28. If you're still having issues after following the steps in there then please let me know.

**Closed by magico13** 2021-02-11 20:31 UTC
