### ISSUE TITLE
Error in home-assistant.log

### ISSUE THREAD

**Issue by jkjunk42** [magico13/ha-emporia-vue#20] opened 2020-11-13 22:45 UTC
2020-11-13 13:53:09 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/__init__.py, line 61: result = vue.login(username=email, password=password)

**Comment by magico13** [comment] 2020-11-13 22:48
Closing as duplicate of #2 but thank you for the report.

**Closed by magico13** 2020-11-13 22:48 UTC
