### ISSUE TITLE
HA startup errors

### ISSUE THREAD

**Issue by DarwinData** [magico13/ha-emporia-vue#10] opened 2020-07-24 20:12 UTC
Hi, 
thanks for the wonderful component.  I love it.
It seems to work ok but at HA startup I get the following errors:

`
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 3:55:23 PM (9 occurrences)
Last logged: 3:55:26 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/__init__.py, line 61: result = vue.login(username=email, password=password)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/sensor.py, line 15: vue_devices = vue.get_devices()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/sensor.py, line 20: device = vue.populate_device_properties(device)
`
Just thought that you should know.
thanks!

**Comment by haddood** [comment] 2020-07-28 05:15
same here:

`Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: July 27, 2020, 6:48:29 PM (9 occurrences)
Last logged: July 27, 2020, 6:48:59 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/__init__.py, line 61: result = vue.login(username=email, password=password)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/sensor.py, line 15: vue_devices = vue.get_devices()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for emporia_vue doing I/O at custom_components/emporia_vue/sensor.py, line 20: device = vue.populate_device_properties(device)`

**Comment by magico13** [comment] 2020-07-28 14:18
I'm gonna mark this as duplicate of #2 but thank you for the reports and the extra info!

**Closed by magico13** 2020-07-28 14:18 UTC
Labels: duplicate
